---
title: "ridge_CV"
author: "Millie Zhu"
date: "12/20/2022"
output: html_document
---

```{r}
load('/Users/macbookpro/Desktop/machine_learning/groupass/bookings_train.RData')
library("tidymodels")
library("themis")
library("knitr")
library("ranger")
library("doParallel")
library("vip")
library("skimr")
library("corrplot")
library("ggridges")
library("forcats")
library("vip")
library("bonsai")
library("lightgbm")
library("xgboost")
library("ggplot2")

require("lubridate")

```
# preliminary data preprocessing
```{r}
tst <- c(bookings_train$arrival_date_month)
bookings_train$arrival_date_month_numb <- match(tst,month.name)

bookings_train$date_col <- as.Date(ISOdate(year = bookings_train$arrival_date_year, month = bookings_train$arrival_date_month_numb, day = bookings_train$arrival_date_day_of_month))

bookings_train$arrival_date_day_of_week <- wday(bookings_train$date_col)

bookings_train$arrival_date_day_of_week <- as.factor(bookings_train$arrival_date_day_of_week)
bookings_train$got_reserved_room <- as.numeric(bookings_train$reserved_room_type == bookings_train$assigned_room_type)

bookings_train$got_reserved_room <- as.factor(bookings_train$got_reserved_room)
bookings_train$arrival_date_year <- as.factor(bookings_train$arrival_date_year)
bookings_train$arrival_date_month <- as.factor(bookings_train$arrival_date_month)
bookings_train$arrival_date_week_number <- as.factor(bookings_train$arrival_date_week_number)
bookings_train$arrival_date_day_of_month <- as.factor(bookings_train$arrival_date_day_of_month)
bookings_train$reserved_room_type <- as.factor(bookings_train$reserved_room_type)
bookings_train$assigned_room_type <- as.factor(bookings_train$assigned_room_type)
bookings_train$country <- as.factor(bookings_train$country)

bookings_train$arrival_date_day_of_week <- as.numeric(bookings_train$arrival_date_day_of_week)
bookings_train$arrival_date_month_numb <- as.numeric(bookings_train$arrival_date_month_numb)
bookings_train$arrival_date_week_number <- as.numeric(bookings_train$arrival_date_week_number)
bookings_train$country <- fct_lump_min(as.factor(bookings_train$country), min=200, other_level = "Other")
bookings_train <- bookings_train %>% 
  filter(!(stays_in_weekend_nights == 0 & stays_in_week_nights == 0))

bookings_train <- bookings_train %>% 
  filter(!(stays_in_weekend_nights == 0 & stays_in_week_nights == 0)) %>% 
  filter(adults != 0)

bookings_train <- bookings_train %>% 
  filter(!(adr < 0))

```

# split the data

```{r}
set.seed(42)
bookings_train_split <- initial_split(data = bookings_train, prop = 0.80, 
                                      strata = is_cancelled)
bookings_train_train <- training(bookings_train_split)
bookings_train_test <- testing(bookings_train_split)
print(bookings_train_train %>% count(is_cancelled) %>% 
        mutate(prop = n / sum(n)))
print(bookings_train_test %>% count(is_cancelled) %>% 
        mutate(prop = n / sum(n)))
```
# Preprocessing reciepe

```{r}
recipe_prelim <- recipe(is_cancelled ~ ., data = bookings_train) %>% 
  step_novel('assigned_room_type') %>%
  update_role( "date_col", "arrival_date_month", "babies",  "arrival_date_day_of_month", "days_in_waiting_list", new_role = "metadata") %>%
  step_harmonic('arrival_date_week_number',frequency=1,cycle_size=53, role='predictor') %>%
  step_harmonic('arrival_date_month_numb',frequency=1,cycle_size=12, role='predictor') %>%   
  step_harmonic('arrival_date_day_of_week',frequency=1,cycle_size=7, role='predictor') %>%   
  step_impute_mode("country") %>%
  step_normalize(all_numeric_predictors())%>%
  step_dummy(all_nominal_predictors())
```
#define metrics
```{r}
class_metrics <- metric_set(accuracy, bal_accuracy, recall, precision, f_meas, specificity)
```

#cross validation
```{r}
set.seed(42)
cv_folds <- bookings_train_train %>% vfold_cv(v = 10, strata = is_cancelled)
```

# ridge model set up
```{r}
ridge_logreg <- logistic_reg(penalty = tune(), mixture = 0) %>%
  set_engine("glmnet")
ridge_logreg
```
# set the tuning grid
```{r}
grid_ridge <- tibble(penalty = 10^(seq(from = -2.5, to = 2, length.out = 100)))
grid_ridge
```
# specify the workflow
```{r}
ridge_wf <- workflow() %>% 
  add_recipe(recipe_prelim) %>% 
  add_model(ridge_logreg)
ridge_wf
```
# tune the model
```{r, results="hide"}
ridge_tune <- ridge_wf %>% 
  tune_grid(resamples = cv_folds, 
            grid = grid_ridge,
            metrics = class_metrics)
ridge_tune_metrics <- ridge_tune %>% 
  collect_metrics()

ridge_tune_metrics %>% filter(.metric == "f_meas") %>% 
  ggplot(aes(x = penalty, y = mean, 
             ymin = mean - std_err, ymax = mean + std_err)) + 
  geom_errorbar(alpha = 0.5) + 
  geom_point() + 
  scale_x_log10() + 
  labs(y = "Accuracy", x = expression(lambda))
```

# select the model 
```{r}
ridge_1se_model <- ridge_tune %>% 
  select_by_one_std_err(metric = "f_meas", desc(penalty))
ridge_1se_model

```

# finalize the workflow
```{r}
ridge_wf_tuned <- 
  ridge_wf %>% 
  finalize_workflow(ridge_1se_model)
ridge_wf_tuned
```
